<%
String path = request.getContextPath();
System.out.println(path);
%>
<script src="<%=path%>/js/check.js" type="text/javascript"></script>
<script src="<%=path%>/js/common.js" type="text/javascript"></script>

<script src="<%=path%>/js/formValid/jquery_last.js" type="text/javascript"></script>
<script src="<%=path%>/js/formValid/formValidator.js" type="text/javascript" charset="UTF-8"></script>
<script src="<%=path%>/js/formValid/formValidatorRegex.js" type="text/javascript" charset="UTF-8"></script>
<script  src="<%=path%>/js/calendar/WdatePicker.js" type="text/javascript"></script>
<script type="text/javascript" src="<%=path%>/js/ymPrompt/ymPrompt_source.js"></script>
<link type="text/css" rel="stylesheet" href="<%=path%>/js/formValid/style/validator.css"></link>
<link type="text/css" rel="stylesheet" href="<%=path%>/js/ymPrompt/skin/simple/ymPrompt.css"></link>

<script type="text/javascript" src="<%=path%>/js/lhgcore.min.js"></script>
<script type="text/javascript" src="<%=path%>/js/lhgdialog.js"></script>

<script src="<%=path%>/js/jquery-1.4.2.min.js" type="text/javascript"></script>
<script src="<%=path%>/js/jquery.cookie.js" type="text/javascript"></script>
<link href="<%=path %>/css/common.css" rel="stylesheet" type="text/css">
<link href="<%=path %>/css/sub.css" rel="stylesheet" type="text/css">
<link href="<%=path %>/css/layout_contents.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" type="text/css" href="<%=path%>/extjs/resources/css/ext-all.css" />
<link rel="stylesheet" type="text/css" href="<%=path%>/extjs/resources/css/ext-patch.css" />
<link rel="stylesheet" type="text/css" href="<%=path%>/extjs/UploadDialog/css/Ext.ux.UploadDialog.css" />
<script type="text/javascript" src="<%=path%>/extjs/adapter/jquery/jquery.js" ></script>
<script type="text/javascript" src="<%=path%>/extjs/adapter/jquery/ext-jquery-adapter.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/ext-all.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/ext-lang-zh_CN.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/TabCloseMenu.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/TreeCheckNodeUI.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/ComboBoxPanel.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/ComboBoxGrid.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/StudentWindows.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/UserWindows.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/StudentWin.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/MonthPicker.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/UploadDialog/Ext.ux.UploadDialog.js"></script>
<script type="text/javascript" src="<%=path%>/extjs/UploadDialog/locale/ru.utf-8_zh.js"></script>  
<style type="text/css" media="all">
@import url("<%=path%>/css/layout.css");
@import url("<%=path%>/css/common.css");
@import url("<%=path%>/css/layout_contents.css");
</style>